CREATE TABLE IF NOT EXISTS revenue_recognition_rules (
  id UUID PRIMARY KEY,
  rule_key VARCHAR(100) NOT NULL UNIQUE,
  revenue_type VARCHAR(50) NOT NULL,
  trigger_event VARCHAR(80) NOT NULL,
  recognition_method VARCHAR(30) NOT NULL DEFAULT 'point_in_time',
  ledger_account_id UUID REFERENCES payment_accounts(id) ON DELETE SET NULL,
  deferred_account_id UUID REFERENCES payment_accounts(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  effective_to TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS revenue_schedules (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL,
  payment_id UUID,
  rule_id UUID NOT NULL REFERENCES revenue_recognition_rules(id),
  revenue_type VARCHAR(50) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  gross_minor BIGINT NOT NULL DEFAULT 0,
  recognized_minor BIGINT NOT NULL DEFAULT 0,
  deferred_minor BIGINT NOT NULL DEFAULT 0,
  reversed_minor BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'scheduled',
  recognition_date DATE,
  source_reference VARCHAR(160),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(order_id, revenue_type, source_reference)
);
CREATE INDEX IF NOT EXISTS revenue_schedules_status_idx ON revenue_schedules(status, recognition_date);
CREATE TABLE IF NOT EXISTS recognized_revenue_events (
  id UUID PRIMARY KEY,
  revenue_schedule_id UUID NOT NULL REFERENCES revenue_schedules(id) ON DELETE CASCADE,
  event_type VARCHAR(30) NOT NULL,
  amount_minor BIGINT NOT NULL,
  currency VARCHAR(3) NOT NULL,
  ledger_transaction_id UUID REFERENCES ledger_transactions(id) ON DELETE SET NULL,
  event_reference VARCHAR(160) NOT NULL UNIQUE,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS order_economics (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL UNIQUE,
  vendor_id UUID,
  customer_id UUID,
  mzaya_id UUID,
  city_code VARCHAR(60),
  service_category VARCHAR(60),
  currency VARCHAR(3) NOT NULL,
  gross_order_value_minor BIGINT NOT NULL DEFAULT 0,
  merchandise_value_minor BIGINT NOT NULL DEFAULT 0,
  platform_revenue_minor BIGINT NOT NULL DEFAULT 0,
  delivery_revenue_minor BIGINT NOT NULL DEFAULT 0,
  procurement_revenue_minor BIGINT NOT NULL DEFAULT 0,
  discounts_minor BIGINT NOT NULL DEFAULT 0,
  taxes_minor BIGINT NOT NULL DEFAULT 0,
  gateway_fees_minor BIGINT NOT NULL DEFAULT 0,
  mzaya_payout_minor BIGINT NOT NULL DEFAULT 0,
  vendor_settlement_minor BIGINT NOT NULL DEFAULT 0,
  refund_minor BIGINT NOT NULL DEFAULT 0,
  direct_cost_minor BIGINT NOT NULL DEFAULT 0,
  allocated_overhead_minor BIGINT NOT NULL DEFAULT 0,
  contribution_margin_minor BIGINT NOT NULL DEFAULT 0,
  contribution_margin_ratio NUMERIC(12,6),
  net_margin_minor BIGINT NOT NULL DEFAULT 0,
  completed_at TIMESTAMPTZ,
  recalculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS order_economics_dimensions_idx ON order_economics(city_code, service_category, completed_at);
CREATE TABLE IF NOT EXISTS cost_allocation_rules (
  id UUID PRIMARY KEY,
  rule_key VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  source_cost_type VARCHAR(60) NOT NULL,
  target_dimension VARCHAR(40) NOT NULL,
  allocation_method VARCHAR(40) NOT NULL,
  currency VARCHAR(3),
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS cost_allocation_runs (
  id UUID PRIMARY KEY,
  run_reference VARCHAR(120) NOT NULL UNIQUE,
  period_code VARCHAR(20) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  total_source_cost_minor BIGINT NOT NULL DEFAULT 0,
  total_allocated_minor BIGINT NOT NULL DEFAULT 0,
  started_by UUID REFERENCES users(id) ON DELETE SET NULL,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  error_message VARCHAR(1000),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS profitability_snapshots (
  id UUID PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  dimension_type VARCHAR(40) NOT NULL,
  dimension_value VARCHAR(160) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  order_count INTEGER NOT NULL DEFAULT 0,
  gross_order_value_minor BIGINT NOT NULL DEFAULT 0,
  recognized_revenue_minor BIGINT NOT NULL DEFAULT 0,
  direct_cost_minor BIGINT NOT NULL DEFAULT 0,
  allocated_overhead_minor BIGINT NOT NULL DEFAULT 0,
  contribution_margin_minor BIGINT NOT NULL DEFAULT 0,
  contribution_margin_ratio NUMERIC(12,6),
  net_margin_minor BIGINT NOT NULL DEFAULT 0,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(snapshot_date, dimension_type, dimension_value, currency)
);
