const router=require('express').Router();
const {authenticate}=require('../middleware/auth.middleware');
const {validateRequest}=require('../middleware/validateRequest');
const controller=require('../controllers/chat.controller');
const v=require('../validators/chat.validator');
router.use(authenticate);
router.get('/:conversationId',validateRequest(v.conversationIdParamsSchema,'params'),validateRequest(v.chatQuerySchema,'query'),controller.getChat);
router.post('/:conversationId/messages',validateRequest(v.conversationIdParamsSchema,'params'),validateRequest(v.sendMessageSchema,'body'),controller.send);
router.patch('/:conversationId/read',validateRequest(v.conversationIdParamsSchema,'params'),validateRequest(v.markReadSchema,'body'),controller.read);
module.exports=router;